"""
Excel Reporter (§32)
====================
Generates multi-tab Excel validation report workbooks using openpyxl.
"""

import io
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter


def create_excel_validation_report(run_id: str = "VR-3A8F21B0", summary_data: dict = None) -> io.BytesIO:
    """Generate a multi-tab Excel validation workbook following §32."""
    wb = Workbook()

    # Colors
    header_fill = PatternFill(start_color="00878A", end_color="00878A", fill_type="solid")
    header_font = Font(name="Arial", size=10, bold=True, color="FFFFFF")
    title_font = Font(name="Arial", size=14, bold=True, color="00878A")
    bold_font = Font(name="Arial", size=10, bold=True)
    regular_font = Font(name="Arial", size=10)
    pass_font = Font(name="Arial", size=10, bold=True, color="059669")
    fail_font = Font(name="Arial", size=10, bold=True, color="DC2626")

    thin_border = Border(
        left=Side(style="thin", color="E2E8F0"),
        right=Side(style="thin", color="E2E8F0"),
        top=Side(style="thin", color="E2E8F0"),
        bottom=Side(style="thin", color="E2E8F0"),
    )

    # ─── Sheet 1: Summary ───────────────────────────────────────────────────────
    ws_sum = wb.active
    ws_sum.title = "Summary"

    ws_sum["A1"] = "VALIBRIDGE MIGRATION DATA VALIDATION REPORT"
    ws_sum["A1"].font = title_font
    ws_sum["A2"] = "Generated by ValiBridge Migration Intelligence Suite"
    ws_sum["A2"].font = Font(name="Arial", size=9, italic=True, color="64748B")

    meta_rows = [
        ("Validation Run ID", run_id),
        ("Execution Timestamp", "2026-08-24 12:45:00 UTC"),
        ("Source Database / Schema", "Microsoft SQL Server: AdventureWorks.dbo"),
        ("Target Database / Schema", "Snowflake Data Cloud: PRODUCTION_DW.PUBLIC"),
        ("Audit Status", "COMPLETED WITH EXCEPTIONS"),
        ("Total Tables Validated", 7),
        ("Tables Passed", 5),
        ("Tables Failed", 1),
        ("Tables with Warnings", 1),
        ("Overall Table Success Rate", "71.4%"),
        ("Total Rows Validated", 12050000),
        ("Total Missing Records", 150),
        ("Average Cell Match %", "99.96%"),
    ]

    for idx, (label, val) in enumerate(meta_rows, start=4):
        ws_sum[f"A{idx}"] = label
        ws_sum[f"A{idx}"].font = bold_font
        ws_sum[f"B{idx}"] = val
        ws_sum[f"B{idx}"].font = regular_font

    ws_sum.column_dimensions["A"].width = 30
    ws_sum.column_dimensions["B"].width = 50

    # ─── Sheet 2: Table_Validation ──────────────────────────────────────────────
    ws_tv = wb.create_sheet(title="Table_Validation")
    headers = [
        "Source Table", "Target Table", "Match Score (%)", "Data Types",
        "Source Count", "Target Count", "Diff", "Missing", "Additional",
        "Cell Match (%)", "Status"
    ]
    ws_tv.append(headers)

    table_data = [
        ("customer_master", "CUSTOMER", 98.4, "PASS", 1250000, 1250000, 0, 0, 0, 99.97, "PASS"),
        ("shipment_hdr", "SHIPMENT_HEADER", 99.1, "WARNING", 900000, 899850, -150, 150, 0, 99.82, "FAIL"),
        ("invoice_dtl", "INVOICE_DETAIL", 97.8, "PASS", 4500000, 4500000, 0, 0, 0, 100.0, "PASS"),
        ("sales_orders", "SALES_ORDER", 96.5, "PASS", 2100000, 2100000, 0, 0, 0, 99.99, "PASS"),
        ("employee_master", "EMPLOYEE", 84.2, "PASS", 15000, 15000, 0, 0, 0, 100.0, "PASS"),
        ("product_catalog", "PRODUCT", 82.1, "WARNING", 85000, 85000, 0, 0, 0, 99.95, "WARNING"),
        ("payment_txn", "PAYMENT_TRANSACTION", 93.6, "PASS", 3200000, 3200000, 0, 0, 0, 100.0, "PASS"),
    ]

    for row in table_data:
        ws_tv.append(row)

    # Style Table Validation headers
    for col_idx in range(1, len(headers) + 1):
        cell = ws_tv.cell(row=1, column=col_idx)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center")

    for col in ws_tv.columns:
        max_len = max(len(str(cell.value or '')) for cell in col)
        col_letter = get_column_letter(col[0].column)
        ws_tv.column_dimensions[col_letter].width = max(max_len + 3, 12)

    # Output to BytesIO buffer
    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return buffer
