services:
  - type: web
    name: cozmatch-backend
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8000
